#Unit-3 Data Wrangling

##Experiment - 12: To Perform Preprocessing on a dataset and dealing with missing values
###Name-Bedang Das
###Prn-25070123031
###Batch-A2

In [ ]:
import pandas as pd
import numpy as np

df1=pd.DataFrame({"C1":[11,21,np.nan],"C2":[12,np.nan,np.nan],"C3":[13,23,33]})
df1

     C1    C2  C3
0  11.0  12.0  13
1  21.0   NaN  23
2   NaN   NaN  33

In [ ]:
#To check is empty spaces or not ?
df1.isnull()

      C1     C2     C3
0  False  False  False
1  False   True  False
2   True   True  False

In [ ]:
#to check how many na entries are there
df1.isna().sum()

C1    1
C2    2
C3    0
dtype: int64

In [ ]:
#Drop NaN rows
df1.dropna()
print(df1)
df1

     C1    C2  C3
0  11.0  12.0  13
1  21.0   NaN  23
2   NaN   NaN  33

     C1    C2  C3
0  11.0  12.0  13
1  21.0   NaN  23
2   NaN   NaN  33

In [ ]:
df1.fillna(value="Default")

        C1       C2  C3
0     11.0     12.0  13
1     21.0  Default  23
2  Default  Default  33

In [ ]:
#To use the mean values to fil the Nan Values with mean of coulumn
df1.fillna(df1.mean())
df1

     C1    C2  C3
0  11.0  12.0  13
1  21.0   NaN  23
2   NaN   NaN  33

In [ ]:
#Data Base 1
import pandas as pd
data = {
    "RollNo:":[1,2,3,4,5,6,7,8,9,10],
    "Name:":["A","B","C","D","E","F","G","H","I","J"],
    "Marks":[20,34,54,65,76,87,"24",65,"-",34],
    "Age":[20,21,22,23,24,25,26,27,28,29],
    "Department":["cse","cse","cse","ece","cse","cse","civil","cse","chemical","cse"],
    "admisssion date":["1-04-2023","3-05-2004","5-09-2034","6-09-2024","23-03-2024","09-08-2029","27-09-2016","12-09-2024","03-04-2023","19-03-2025",]

}
df2=pd.DataFrame(data)
df2

#save as csv file
df2.to_csv("data.csv",index=False)

In [ ]:
#Replace "-" with NaN to mark missing values
df2.replace("-",np.nan,inplace=True)
df2

   RollNo: Name:  Marks  Age Department admisssion date
0        1     A   20.0   20        cse       1-04-2023
1        2     B   34.0   21        cse       3-05-2004
2        3     C   54.0   22        cse       5-09-2034
3        4     D   65.0   23        ece       6-09-2024
4        5     E   76.0   24        cse      23-03-2024
5        6     F   87.0   25        cse      09-08-2029
6        7     G   24.0   26      civil      27-09-2016
7        8     H   65.0   27        cse      12-09-2024
8        9     I    NaN   28   chemical      03-04-2023
9       10     J   34.0   29        cse      19-03-2025

In [ ]:
#Conver columns to numeric where needed
df2["Marks"]=pd.to_numeric(df2["Marks"],errors="coerce")
df2["Age"]=pd.to_numeric(df2["Age"],errors="coerce")


df2['RollNo:']=pd.to_numeric(df2['RollNo:'])
df2.dtypes
df2
#

   RollNo: Name:  Marks  Age Department admisssion date
0        1     A   20.0   20        cse       1-04-2023
1        2     B   34.0   21        cse       3-05-2004
2        3     C   54.0   22        cse       5-09-2034
3        4     D   65.0   23        ece       6-09-2024
4        5     E   76.0   24        cse      23-03-2024
5        6     F   87.0   25        cse      09-08-2029
6        7     G   24.0   26      civil      27-09-2016
7        8     H   65.0   27        cse      12-09-2024
8        9     I    NaN   28   chemical      03-04-2023
9       10     J   34.0   29        cse      19-03-2025

In [ ]:
#cHECK MISSING VALUES IN EACH COULUMN
print("\nMissing values")
df2.isnull().sum()
#

Missing values

RollNo:            0
Name:              0
Marks              1
Age                0
Department         0
admisssion date    0
dtype: int64

In [ ]:
#Fill the missing values with mean
df2.fillna(df2["Age"].mean(),inplace=True)
df2
#fill the missing values with meadian
df2.fillna(df2["Marks"].median(),inplace=True)
df2
#Fill the department with mode
df2["Department"].fillna(df2["Department"].mode()[0],inplace=True)
df2

/tmp/ipykernel_574/3925261269.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2["Department"].fillna(df2["Department"].mode()[0],inplace=True)

   RollNo: Name:  Marks  Age Department admisssion date
0        1     A   20.0   20        cse       1-04-2023
1        2     B   34.0   21        cse       3-05-2004
2        3     C   54.0   22        cse       5-09-2034
3        4     D   65.0   23        ece       6-09-2024
4        5     E   76.0   24        cse      23-03-2024
5        6     F   87.0   25        cse      09-08-2029
6        7     G   24.0   26      civil      27-09-2016
7        8     H   65.0   27        cse      12-09-2024
8        9     I   24.5   28   chemical      03-04-2023
9       10     J   34.0   29        cse      19-03-2025

In [ ]:
#Now check if we have any empty spaces
print("\nMissing values")
df2.isnull().sum()
#

Missing values

RollNo:            0
Name:              0
Marks              0
Age                0
Department         0
admisssion date    0
dtype: int64

In [ ]:
#Fix incosistent text formatting
df2["Department"]=df2["Department"].str.upper()
df2

   RollNo: Name:  Marks  Age Department admisssion date
0        1     A   20.0   20        CSE       1-04-2023
1        2     B   34.0   21        CSE       3-05-2004
2        3     C   54.0   22        CSE       5-09-2034
3        4     D   65.0   23        ECE       6-09-2024
4        5     E   76.0   24        CSE      23-03-2024
5        6     F   87.0   25        CSE      09-08-2029
6        7     G   24.0   26      CIVIL      27-09-2016
7        8     H   65.0   27        CSE      12-09-2024
8        9     I   24.5   28   CHEMICAL      03-04-2023
9       10     J   34.0   29        CSE      19-03-2025

In [ ]:
#Convert admssion date to dd-mm-yyyy format
df2["admisssion date"]=pd.to_datetime(df2["admisssion date"],error="coerce")
df2

TypeError: to_datetime() got an unexpected keyword argument 'error'

In [ ]:
#To save clean data dataset
df2.to_csv("clean_data.csv",index=False)
#

#Cars_93

In [ ]:
#Import the file
df = pd.read_csv("/content/Cars93.csv")
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
#check for missing values in all the coulumns
df.isna().sum()
#

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [ ]:
#Imputing the missing values
df["Luggage.room"]=df["Luggage.room"].fillna(df["Luggage.room"].mean())
df.isna().sum()
df["Rear.seat.room"]=df["Rear.seat.room"].fillna(df["Rear.seat.room"].mean())
df.isna().sum()
df["AirBags"]=df["AirBags"].fillna(value="Driver and codriver")
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,<bound method Series.mean of 0 ...,140,5,26.5,11.000000
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.000000
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.000000
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.000000
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.000000
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,<bound method Series.mean of 0 ...,109,7,34.0,13.890244
89,Volkswagen,Passat,Compact,20.0,21,<bound method Series.mean of 0 ...,134,5,31.5,14.000000
90,Volkswagen,Corrado,Sporty,23.3,18,<bound method Series.mean of 0 ...,178,4,26.0,15.000000
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.000000
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.000000

In [ ]:
#Convert back to csv
df.to_csv("updated_cars_93",index=False)